### ISSUE TITLE
Get stop button to reset balances

### ISSUE THREAD

**Issue by krispyk84** [krispyk84/BitcoinTrader#12]

**Comment by borovez** [comment]
I reset the balances, I also restart the main loop. I created a function called startMainLoop, this function is the while(!STOP) loop that was in main. After stop is called and then START, the loop never executes unless it is called again, so that is why I put it in a function which is called after START has been called after a STOP.

Please, double check the HelpMethods for the defaultBalances function. This function is what resets all of the values and resets the textfields. I didn't reset the last transaction fields though, the naming for the textfields is hard to understand...
